###
#
# For more information about makefiles, check here:
#     http://www.gnu.org/software/make/manual/make.html
#
# Original makefile by Shane Culpepper, modified by David Shaw
###

# The name of the applications we're trying to generate
TARGET_LL = set_llist
TARGET_AR = set_array
TARGET_BT = set_btree
TARGET_HT = set_hash


SRC_LL = main.c util.c set_llist.c
SRC_AR = main.c util.c set_array.c
SRC_BT = main.c util.c set_btree.c
SRC_HT = main.c util.c set_hash.c
HDR = util.h set.h

OBJ_LL := $(SRC_LL:.c=.o)
OBJ_AR := $(SRC_AR:.c=.o)
OBJ_BT := $(SRC_BT:.c=.o)
OBJ_HT := $(SRC_HT:.c=.o)

# These variables are used by make in all of it's automatic rules.
# Specifically, use CFLAGS for the "-g -O0" option if you want to do debugging,
# and LDFLAGS for the "-lm" option if you are using the math library.
CC = gcc
#CFLAGS = -W -Wall -ansi -O3 -D_XOPEN_SOURCE=500
CFLAGS = -W -Wall -ansi -g -O0 -D_XOPEN_SOURCE=500
LDFLAGS = -lm

all : $(TARGET_LL) $(TARGET_AR) $(TARGET_BT) $(TARGET_HT)

$(TARGET_LL) : $(OBJ_LL)
	$(CC) $(LDFLAGS) -o $@ $(OBJ_LL)

$(TARGET_AR) : $(OBJ_AR)
	$(CC) $(LDFLAGS) -o $@ $(OBJ_AR)

$(TARGET_BT) : $(OBJ_BT)
	$(CC) $(LDFLAGS) -o $@ $(OBJ_BT)

$(TARGET_HT) : $(OBJ_HT)
	$(CC) $(LDFLAGS) -o $@ $(OBJ_HT)


# This generates the dependencies between your various .c and .h files, using
# the c compiler's -MM option.
depend : $(SRC_LL) $(SRC_AR) $(SRC_BT) $(SRC_HT) $(HDR)
	$(CC) $(CFLAGS) -MM $(SRC_LL) > depend
	$(CC) $(CFLAGS) -MM $(SRC_AR) > depend
	$(CC) $(CFLAGS) -MM $(SRC_BT) > depend
	$(CC) $(CFLAGS) -MM $(SRC_HT) > depend

# This includes the dependencies made with the previous rule, and in fact forces
# them to be generated.
-include depend

# The rules below clean up any files generated by the make process.  clean
# should be run to clear out the temporary files, and clobber should be run if
# you modify your makefile (for example to change the CFLAGS or LDFLAGS options)
# so that you can get a clean recompile.
.PHONY : clean

clean :
	-rm -f depend
	-rm -f $(TARGET_LL) $(TARGET_AR) $(TARGET_BT) $(TARGET_HT) $(OBJ_LL) $(OBJ_AR) $(OBJ_BT) $(OBJ_HT)
	-rm -f *~ 
